# Generated by Django 5.2 on 2024-11-15 14:16

import django.db.models.deletion
import lnschema_core.fields
import lnschema_core.ids
import lnschema_core.models
import lnschema_core.users
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cellregistry", "0001_initial"),
        (
            "lnschema_core",
            "0069_alter_artifact__accessor_alter_artifact__hash_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifactcell",
            name="artifact",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_cell",
                to="lnschema_core.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="artifactcell",
            name="cell",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_artifact",
                to="cellregistry.cell",
            ),
        ),
        migrations.AlterField(
            model_name="artifactcell",
            name="created_at",
            field=lnschema_core.fields.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="artifactcell",
            name="created_by",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="artifactcell",
            name="run",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.models.current_run,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.run",
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="created_at",
            field=lnschema_core.fields.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="cell",
            name="created_by",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.user",
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="description",
            field=lnschema_core.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="name",
            field=lnschema_core.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="run",
            field=lnschema_core.fields.ForeignKey(
                blank=True,
                default=lnschema_core.models.current_run,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lnschema_core.run",
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="uid",
            field=lnschema_core.fields.CharField(
                blank=True,
                default=lnschema_core.ids.base62_20,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cell",
            name="updated_at",
            field=lnschema_core.fields.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
